name: github_semantic_geo_partitioning
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - python=3.8
  - pytorch=1.10
  - torchvision=0.11
  - pytorch-lightning>=1.4.2, <=1.5.2
  - msgpack-python
  - pyyaml
  - pandas
  - pip
  - notebook
  - black
  - geopandas
  - ipyleaflet
  - folium
  - pip:
    - s2sphere==0.2.5
    - efficientnet_pytorch==0.7.1
    - pyarrow